title: "Portofolio Samuel Chinson"
email: samuel.chinson@gmail.com
description: >-
  Portofolio Data Science Samuel Chinson – NLP, ML, dan Analisis Data
theme: null
markdown: kramdown
permalink: pretty
